### ISSUE TITLE
plist报错，我是美术完全不懂程序。

### ISSUE THREAD

**Issue by scorpioDC** [justbilt/untp#14]
解析某些plist的时候会报错，我是美术不懂代码，我也看不懂。能解答一下吗。代码如下。
Traceback (most recent call last):
[归档.zip](https://github.com/justbilt/untp/files/1676526/default.zip)

  File "/usr/local/bin/untp", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/untp/untp.py", line 246, in main
    return unpacker(argument.path, image_file = argument.image_file, output_dir = argument.output)
  File "/Library/Python/2.7/site-packages/untp/untp.py", line 104, in unpacker
    dst_image.save(output_path)
  File "/Library/Python/2.7/site-packages/PIL/Image.py", line 1915, in save
    raise ValueError('unknown file extension: {}'.format(ext))
ValueError: unknown file extension: 

附件里有.plist 和 .png

**Comment by justbilt** [comment]
不知道为啥没有收到推送, 找到原因了, plist 中图元没有后缀名, 很好改, 我改完上传一个新的版本.

**Comment by justbilt** [comment]
已经修复并提交了, 我测试是可以正常拆解出图片的, 你可以使用 `pip install -U untp` 升级, 谢谢你的反馈.
