### ISSUE TITLE
解析plist异常

### ISSUE THREAD

**Issue by gydhy8** [justbilt/untp#18]
Traceback (most recent call last):
  File "/usr/local/bin/untp", line 9, in <module>
    load_entry_point('untp==1.1.5', 'console_scripts', 'untp')()
  File "build/bdist.macosx-10.13-intel/egg/untp/untp.py", line 249, in main
  File "build/bdist.macosx-10.13-intel/egg/untp/untp.py", line 55, in unpacker
  File "build/bdist.macosx-10.13-intel/egg/untp/dataparse.py", line 20, in parse_file
  File "build/bdist.macosx-10.13-intel/egg/untp/dataparse.py", line 171, in parse_plistdata
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 301, in __getattr__
    raise AttributeError, attr
AttributeError: textureFileName

**Comment by justbilt** [comment]
能提供下出异常的 plist 文件吗？
