### ISSUE TITLE
Error while unpack jpg item with png image

### ISSUE THREAD

**Issue by justbilt** [justbilt/untp#19]
```Traceback (most recent call last):
  File "/usr/local/bin/untp", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/untp/untp.py", line 244, in main
    return unpacker(argument.path, image_file = argument.image_file, output_dir = argument.output, protection_key = argument.protection)
  File "/usr/local/lib/python2.7/site-packages/untp/untp.py", line 94, in unpacker
    dst_image.save(output_path)
  File "/usr/local/lib/python2.7/site-packages/PIL/Image.py", line 1950, in save
    save_handler(self, fp, filename)
  File "/usr/local/lib/python2.7/site-packages/PIL/JpegImagePlugin.py", line 623, in _save
    raise IOError("cannot write mode %s as JPEG" % im.mode)
IOError: cannot write mode RGBA as JPEG```

**Comment by 18437931018** [comment]
PS C:\Windows\system32> untp
Traceback (most recent call last):
  File "d:\python\app\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\python\app\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\python\app\Scripts\untp.exe\__main__.py", line 5, in <module>
  File "d:\python\app\lib\site-packages\untp\__init__.py", line 3, in <module>
    from untp import unpacker_dir, unpacker
ImportError: cannot import name 'unpacker_dir'

why do it say this

**Comment by justbilt** [comment]
Chinese ? 你是怎么安装 untp 的, 能看下 `d:\python\app\lib\site-packages` 这个目录的结构吗?
