### ISSUE TITLE
ImportError: cannot import name 'unpacker_dir' from 'untp' (d:\users\h5osir\pycharmprojects\plisttopng3\venv\lib\site-packages\untp\__init__.py)

### ISSUE THREAD

**Issue by xiaoxinyi01** [justbilt/untp#22]
(venv) D:\Users\h5osir\PycharmProjects\plistToPNG3>pip install untp
Collecting untp
  Using cached untp-1.1.7-py2.py3-none-any.whl (9.7 kB)
Collecting Pillow
  Using cached Pillow-7.2.0-cp37-cp37m-win_amd64.whl (2.1 MB)
Processing c:\users\h5osir\appdata\local\pip\cache\wheels\d7\b3\1d\5c94c64413b2212f64a297c92f11edd45e4474d08d0220a008\parse-1.15.0-py3-none-any.whl
Installing collected packages: Pillow, parse, untp
Successfully installed Pillow-7.2.0 parse-1.15.0 untp-1.1.7

(venv) D:\Users\h5osir\PycharmProjects\plistToPNG3>untp
Traceback (most recent call last):
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Users\h5osir\PycharmProjects\plistToPNG3\venv\Scripts\untp.exe\__main__.py", line 4, in <module>
  File "d:\users\h5osir\pycharmprojects\plisttopng3\venv\lib\site-packages\untp\__init__.py", line 3, in <module>
    from untp import unpacker_dir, unpacker
ImportError: cannot import name 'unpacker_dir' from 'untp' (d:\users\h5osir\pycharmprojects\plisttopng3\venv\lib\site-packages\untp\__init__.py)

**Comment by justbilt** [comment]
I got that, untp current not work fine on python3, i will fix that in 24h.

**Comment by justbilt** [comment]
This issue is fixed and released with untp 1.1.8, you could got it via `pip install untp --upgrade`.

Thank your feedback.
