### ISSUE TITLE
mistake

### ISSUE THREAD

**Issue by shixiaoshan2000** [justbilt/untp#24]
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Windows\system32>untp
Exception in Tkinter callback
Traceback (most recent call last):
  File "d:\program files\python38\lib\tkinter\__init__.py", line 1892, in __call
__
    return self.func(*args)
  File "d:\program files\python38\lib\site-packages\untp\untp.py", line 214, in
select_file
    unpacker(v, image_file=image_file, protection_key=protection_key)
  File "d:\program files\python38\lib\site-packages\untp\untp.py", line 49, in u
npacker
    data = dataparse.parse_file(data_file, config, extra_data_receiver)
  File "d:\program files\python38\lib\site-packages\untp\dataparse.py", line 20,
 in parse_file
    return parse_plistdata(data)
  File "d:\program files\python38\lib\site-packages\untp\dataparse.py", line 101
, in parse_plistdata
    fmt = _data.metadata.format
AttributeError: 'dict' object has no attribute 'metadata'
Exception in Tkinter callback
Traceback (most recent call last):
  File "d:\program files\python38\lib\tkinter\__init__.py", line 1892, in __call
__
    return self.func(*args)
  File "d:\program files\python38\lib\site-packages\untp\untp.py", line 214, in
select_file
    unpacker(v, image_file=image_file, protection_key=protection_key)
  File "d:\program files\python38\lib\site-packages\untp\untp.py", line 49, in u
npacker
    data = dataparse.parse_file(data_file, config, extra_data_receiver)
  File "d:\program files\python38\lib\site-packages\untp\dataparse.py", line 20,
 in parse_file
    return parse_plistdata(data)
  File "d:\program files\python38\lib\site-packages\untp\dataparse.py", line 101
, in parse_plistdata
    fmt = _data.metadata.format
AttributeError: 'dict' object has no attribute 'metadata'
Exception in Tkinter callback
Traceback (most recent call last):
  File "d:\program files\python38\lib\tkinter\__init__.py", line 1892, in __call
__
    return self.func(*args)
  File "d:\program files\python38\lib\site-packages\untp\untp.py", line 214, in
select_file
    unpacker(v, image_file=image_file, protection_key=protection_key)
  File "d:\program files\python38\lib\site-packages\untp\untp.py", line 49, in u
npacker
    data = dataparse.parse_file(data_file, config, extra_data_receiver)
  File "d:\program files\python38\lib\site-packages\untp\dataparse.py", line 20,
 in parse_file
    return parse_plistdata(data)
  File "d:\program files\python38\lib\site-packages\untp\dataparse.py", line 101
, in parse_plistdata
    fmt = _data.metadata.format
AttributeError: 'dict' object has no attribute 'metadata'

**Comment by shixiaoshan2000** [comment]
i use python 3.8.10
