### ISSUE TITLE
unto failed

### ISSUE THREAD

**Issue by Ring1992** [justbilt/untp#5]
Traceback (most recent call last):
  File "/usr/local/bin/untp", line 9, in <module>
    load_entry_point('untp==1.0.3', 'console_scripts', 'untp')()
  File "/Library/Python/2.7/site-packages/untp-1.0.3-py2.7.egg/EGG-INFO/scripts/untp.py", line 97, in main

UnboundLocalError: local variable 'currten_path' referenced before assignment

**Comment by justbilt** [comment]
it's weird, version 1.0.3 should not contain `currten_path`,  it's contained in newest commit, i don't release it.

could you tell me how you ues untp in command line ?
