### ISSUE TITLE
other format support

### ISSUE THREAD

**Issue by justbilt** [justbilt/untp#9]
https://github.com/ifshuaishuai/texture_unpacker_scirpt/blob/master/unpacker.py

**Comment by 18437931018** [comment]
为什么 我的报这个错

PS C:\Windows\system32> untp
Traceback (most recent call last):
  File "d:\python\app\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\python\app\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\python\app\Scripts\untp.exe\__main__.py", line 5, in <module>
  File "d:\python\app\lib\site-packages\untp\__init__.py", line 3, in <module>
    from untp import unpacker_dir, unpacker
ImportError: cannot import name 'unpacker_dir'
